-- A CONTINUACION SE CREA EL USUARIO DE ADMIN PARA EL PROYECTO AMAROK --

CREATE USER yespinosa WITH PASSWORD 'Yeison01*';

CREATE DATABASE db_amarok WITH OWNER yespinosa;

ALTER USER yespinosa WITH SUPERUSER;
ALTER USER yespinosa WITH CREATEDB;
ALTER USER yespinosa WITH CREATEROLE;

-- A CONTINUACION SE CREA EL ROL DE CLIENTE PARA EL PROYECTO AMAROK --

CREATE USER cliente WITH PASSWORD 'cliente123';  

GRANT CONNECT ON DATABASE db_amarok TO cliente;  

GRANT USAGE ON SCHEMA public TO cliente;  

GRANT SELECT, INSERT, UPDATE ON TABLE cliente TO cliente; 

GRANT SELECT, INSERT ON TABLE venta, redencionpuntos, detalleventa, enviolocal, envionacional TO cliente;

GRANT SELECT ON TABLE ciudad, departamento, tipopago TO cliente;


-- A CONTINUACION SE CREA EL ROL DE MENSAJERO PARA EL PROYECTO AMAROK --

CREATE ROLE mensajero WITH PASSWORD 'mensajero123';

GRANT CONNECT ON DATABASE db_amarok TO mensajero;  

GRANT USAGE ON SCHEMA public TO mensajero;  

GRANT SELECT, INSERT, UPDATE ON TABLE mensajero TO mensajero; 

GRANT SELECT ON TABLE enviolocal, envionacional TO mensajero;